name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TASK_EXECUTOR_IMAGE: ghcr.io/summer-project/task-executor/:${{ github.sha }}
 

jobs:

  build-task-executor:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Task-executor
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./task-executor/Docerfile
        push: true
        tags: ${{ env.TASK_EXECUTOR_IMAGE }}
